### ISSUE TITLE
Post post from the frontend with the plugins

### ISSUE THREAD

**Issue by anton-team** [ajvillegas/image-gallery-metabox#2]
Hello,

I have been using the plugins and it is so much, congratulations.

I have a concern ...

How can I create a form to publish a post from the frontend using the same parameters of the plugins, that is ...

I want to publish a post from the frontend where I can attach images as I do from admin.

Any idea of how I can do it integrated with the pugins.

In the form I would like to have: Attached images, a highlighted image, title of the post and the description.

If this is possible, please let me know.
Thanks in advance

**Comment by ajvillegas** [comment]
Hi @antonagency,

Unfortunately using the Image Gallery meta box in the front-end is not something the plugin supports right now.

You might want to take a look at [CMB2](https://github.com/CMB2) or [Advanced Custom Fields Pro](https://www.advancedcustomfields.com/pro/), both of which let you integrate meta boxes in the front-end. Advanced Custom Fields Pro even has a gallery meta box similar to Image Gallery Metabox.

I hope this helps and good luck.
